employees=[{"eid":1,"ename":"Alis","gender":"Agender"},
{"eid":2,"ename":"Erinn","gender":"Non-binary"},
{"eid":3,"ename":"Deonne","gender":"Female"},
{"eid":4,"ename":"John","gender":"Male"},
{"eid":5,"ename":"Corbet","gender":"Male"},
{"eid":6,"ename":"Barde","gender":"Polygender"},
{"eid":7,"ename":"Kare","gender":"Female"},
{"eid":8,"ename":"Alfy","gender":"Male"},
{"eid":9,"ename":"Mason","gender":"Male"},
{"eid":10,"ename":"Aldous","gender":"Male"},
{"eid":11,"ename":"Hamnet","gender":"Male"},
{"eid":12,"ename":"Roobbie","gender":"Female"},
{"eid":13,"ename":"Darn","gender":"Male"},
{"eid":14,"ename":"Daniel","gender":"Male"},
{"eid":15,"ename":"Jesse","gender":"Genderqueer"},
{"eid":16,"ename":"Gianni","gender":"Male"},
{"eid":17,"ename":"Neala","gender":"Female"},
{"eid":18,"ename":"Ruddie","gender":"Male"},
{"eid":19,"ename":"Miguel","gender":"Male"},
{"eid":20,"ename":"Erena","gender":"Female"},
{"eid":21,"ename":"Maridel","gender":"Female"},
{"eid":22,"ename":"Euphemia","gender":"Female"},
{"eid":23,"ename":"Darla","gender":"Female"},
{"eid":24,"ename":"Etta","gender":"Female"},
{"eid":25,"ename":"Adolf","gender":"Male"},
{"eid":26,"ename":"Dina","gender":"Female"},
{"eid":27,"ename":"Deeyn","gender":"Female"},
{"eid":28,"ename":"Davy","gender":"Male"},
{"eid":29,"ename":"Shawnee","gender":"Female"},
{"eid":30,"ename":"Andrei","gender":"Female"},
{"eid":31,"ename":"Reynard","gender":"Male"},
{"eid":32,"ename":"Morten","gender":"Male"},
{"eid":33,"ename":"Clywd","gender":"Male"},
{"eid":34,"ename":"Faustine","gender":"Female"},
{"eid":35,"ename":"Stan","gender":"Male"},
{"eid":36,"ename":"Gaylord","gender":"Male"},
{"eid":37,"ename":"Fowler","gender":"Male"},
{"eid":38,"ename":"Emmerich","gender":"Male"},
{"eid":39,"ename":"Romona","gender":"Female"},
{"eid":40,"ename":"Tarrah","gender":"Female"},
{"eid":41,"ename":"Sophi","gender":"Female"},
{"eid":42,"ename":"Tracy","gender":"Female"},
{"eid":43,"ename":"Belvia","gender":"Female"},
{"eid":44,"ename":"Agnes","gender":"Female"},
{"eid":45,"ename":"Marian","gender":"Female"},
{"eid":46,"ename":"Mara","gender":"Female"},
{"eid":47,"ename":"Sarita","gender":"Genderqueer"},
{"eid":48,"ename":"Hayes","gender":"Male"},
{"eid":49,"ename":"Spense","gender":"Male"},
{"eid":50,"ename":"Atlanta","gender":"Female"},
{"eid":51,"ename":"Monti","gender":"Male"},
{"eid":52,"ename":"Jacqueline","gender":"Genderfluid"},
{"eid":53,"ename":"Paulette","gender":"Female"},
{"eid":54,"ename":"Napoleon","gender":"Male"},
{"eid":55,"ename":"Maureen","gender":"Female"},
{"eid":56,"ename":"Caro","gender":"Female"},
{"eid":57,"ename":"Tadd","gender":"Male"},
{"eid":58,"ename":"Sayer","gender":"Male"},
{"eid":59,"ename":"Benedict","gender":"Male"},
{"eid":60,"ename":"Alanna","gender":"Bigender"},
{"eid":61,"ename":"Deloria","gender":"Female"},
{"eid":62,"ename":"Giuseppe","gender":"Male"},
{"eid":63,"ename":"Ruthe","gender":"Female"},
{"eid":64,"ename":"Kris","gender":"Non-binary"},
{"eid":65,"ename":"Marjory","gender":"Female"},
{"eid":66,"ename":"Seth","gender":"Male"},
{"eid":67,"ename":"Gracia","gender":"Female"},
{"eid":68,"ename":"Delora","gender":"Female"},
{"eid":69,"ename":"Putnam","gender":"Male"},
{"eid":70,"ename":"Ab","gender":"Male"},
{"eid":71,"ename":"Tammie","gender":"Male"},
{"eid":72,"ename":"Marcos","gender":"Male"},
{"eid":73,"ename":"Zandra","gender":"Female"},
{"eid":74,"ename":"Yardley","gender":"Agender"},
{"eid":75,"ename":"Brose","gender":"Male"},
{"eid":76,"ename":"Koo","gender":"Female"},
{"eid":77,"ename":"Glennie","gender":"Female"},
{"eid":78,"ename":"Hymie","gender":"Male"},
{"eid":79,"ename":"Marabel","gender":"Female"},
{"eid":80,"ename":"Koo","gender":"Female"},
{"eid":81,"ename":"Iosep","gender":"Male"},
{"eid":82,"ename":"Ladonna","gender":"Female"},
{"eid":83,"ename":"Frants","gender":"Bigender"},
{"eid":84,"ename":"Garland","gender":"Female"},
{"eid":85,"ename":"Onida","gender":"Female"},
{"eid":86,"ename":"Constantin","gender":"Male"},
{"eid":87,"ename":"Elie","gender":"Female"},
{"eid":88,"ename":"Kerr","gender":"Non-binary"},
{"eid":89,"ename":"Tomlin","gender":"Male"},
{"eid":90,"ename":"Riannon","gender":"Female"},
{"eid":91,"ename":"Vinny","gender":"Female"},
{"eid":92,"ename":"Ossie","gender":"Male"},
{"eid":93,"ename":"Blayne","gender":"Male"},
{"eid":94,"ename":"Ransell","gender":"Male"},
{"eid":95,"ename":"Nico","gender":"Male"},
{"eid":96,"ename":"Madelyn","gender":"Female"},
{"eid":97,"ename":"Sandy","gender":"Male"},
{"eid":98,"ename":"Ody","gender":"Male"},
{"eid":99,"ename":"Alaine","gender":"Female"},
{"eid":100,"ename":"Benedetto","gender":"Male"}]
for employee in employees:
     print("employee name",employee['ename'])

for employee in employees:
    if employee['gender']=='Male':
        print("Male employee",employee['ename'])

for employee in employees:
    if employee['gender']=='Female':
     print("Female employee",employee['ename'])
     male_emp=0
    for emp in employees:
        if emp['gender']=='Male':
           male_emp+=1
    print("total male employees are:",male_emp)