id=[5,6,7,8,9,9,10,44,32,23,21]
print(id)
print("maximum:",max(id))
print("minimum:",min(id))
print("sum:",sum(id))
id.sort()
print(id)
id.sort(reverse=True)
print(id)
id1=list(set(id))
print("duplicate numbers:",id1)